name: Crash Report
description: The game crashed on a certain action.
labels: ["Crash"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Before submitting an issue, check if your request has been submitted before. If it has, please don't submit a duplicate.
        In particular, check if it is a [Known Issue](https://github.com/Divine-Journey-2/Divine-Journey-2/issues?q=state%3Aopen%20label%3A"Known%20Issue").
        Then, if you have OptiFine installed and the crash is related to a visual issue, remove OptiFine and confirm that it happens without OptiFine.
        If you are not using the latest version, make sure that the report has not already been [resolved](https://github.com/Divine-Journey-2/Divine-Journey-2/commits/main/).
  - type: input
    id: modpack-version
    attributes:
      label: Modpack version
      description: If you are not using the latest version, make sure that the request has not already been fulfilled.
      placeholder: "Example: 2.X.X"
    validations:
      required: true
  - type: input
    id: java-version
    attributes:
      label: Java version
      description: "Note: if you are using CurseForge as the launcher, due to a bug with CurseForge, you are using Java 1.8.0_51 (check your crash log). As you are using a Java version that dates to late 2015, you will run into a number of issues you wouldn't otherwise."
      placeholder: "Example: 1.8.0_311"
    validations:
      required: true
  - type: input
    id: memory-amount
    attributes:
      label: RAM Allocated
      description: How much RAM did you dedicate to your client and how much RAM does your PC have? Note that 6 GB dedicated and 8 GB total is the bare minimum to run DJ2 - if you have less, that might be the cause of the crash.
      placeholder: "Example: I dedicated 6 GBs and my PC has 8 GBs of RAM."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how the crash happened in a clear and concise way. If it is caused by a specific mod, indicate which one.
    validations:
      required: true
  - type: textarea
    id: crash-location
    attributes:
      label: When did the crash happen?
      description: During startup (at which phase?) / when entering the world / when joining the server / when placing a certain block / ...
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: |
        1. Open the game / Start the modpack / Get into a world / ...
        2. Get the item ... / Go to ... / Open the ... / Place a ... / Break a ... / ...
        3. Continue providing steps as needed
        4. The game crashes. / The server crashes. / ...
    validations:
      required: true
  - type: textarea
    id: crash-report
    attributes:
      label: Minecraft crash report
      description: |
        Crash reports are found in the `your_minecraft_instance/crash-reports` folder.
        If no crash report generated, please include the `your_mincraft_instance/logs/latest.log` file. Note that the latest.log is overwritten every time you launch the game, and so this must happen as soon as you crash.
        You can attach any number of crash reports, but please describe when each of them occurred.
        You can either upload the file directly to github, or use [pastebin](https://pastebin.com/), [paste.ee](https://paste.ee/), [mclogs](https://mclo.gs), or any other paste site.
        **Do not paste the contents of either these files directly into the text box.**
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: input
    id: discord-id
    attributes:
      label: Your Divine Journey 2 Discord Username
      description: If you haven't joined the Discord, this will make it harder to contact you if we need additional info.
      placeholder: "Example: atricos, waitingidly"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make this crash report!
