blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/rH9pyS7
    about: Join the Discord Server! Tech support should primarily occur in the titular channel on the Discord.